export const COMPLETE_CASE_FIELD_DEFAULTS: Record<string, string> = {
  "property.name": "港区グランドタワー",
  "property.furigana": "ミナトクグランドタワー",
  "property.roomNumber": "802",
  "property.postalCode": "1050011",
  "property.address": "東京都港区芝公園 1-2-3",
  "lease.moveInDate": "2026年6月1日",
  "lease.rent": "120000",
  "lease.commonFee": "8000",
  "lease.parkingFee": "15000",
  "lease.monthlyRentTotal": "143000",
  "lease.waterTownFee": "3000",
  "lease.otherMonthlyFee": "5000",
  "lease.deposit": "240000",
  "lease.keyMoney": "120000",
  "lease.insuranceFee": "20000",
  "lease.keyExchangeFee": "33000",
  "lease.cancellationDeduction": "0",
  "applicant.name": "山田 太郎",
  "applicant.furigana": "ヤマダ タロウ",
  "applicant.gender": "男",
  "applicant.spouse": "有",
  "applicant.birthDate": "1990年1月1日",
  "applicant.phone": "090-1234-5678",
  "applicant.mobilePhone": "090-1234-5678",
  "applicant.currentPostalCode": "1410032",
  "applicant.currentAddress": "東京都品川区大崎4-5-6",
  "applicant.residenceYears": "3年",
  "applicant.housingType": "自己所有",
  "applicant.currentRent": "90000",
  "applicant.driverLicenseNumber": "T123456789012",
  "applicant.employerFurigana": "ヤマダショウジ",
  "applicant.employerName": "山田商事株式会社",
  "applicant.employerPhone": "03-1111-2222",
  "applicant.employerPostalCode": "1000005",
  "applicant.employerAddress": "東京都千代田区丸の内1-1-1",
  "applicant.occupation": "IT営業",
  "applicant.employmentType": "正社員",
  "applicant.annualIncome": "650",
  "applicant.monthlyIncome": "55",
  "applicant.yearsEmployed": "3年",
  "applicant.payday": "25",
  "applicant.moveReason": "転勤",
  "guarantor.furigana": "タナカ イチロウ",
  "guarantor.name": "田中 一郎",
  "guarantor.gender": "男",
  "guarantor.spouse": "有",
  "guarantor.relationship": "叔父",
  "guarantor.birthDate": "1960年4月4日",
  "guarantor.postalCode": "1760012",
  "guarantor.address": "東京都練馬区豊玉北5-6-7",
  "guarantor.residenceYears": "20年",
  "guarantor.housingType": "自己所有",
  "guarantor.phone": "090-4444-5555",
  "guarantor.mobilePhone": "090-4444-5555",
  "guarantor.driverLicenseNumber": "G123456789012",
  "guarantor.employerFurigana": "トウキョウセツビ",
  "guarantor.employerName": "東京設備株式会社",
  "guarantor.employerPhone": "03-2222-3333",
  "guarantor.employerAddress": "東京都板橋区板橋1-2-3",
  "guarantor.occupation": "設備管理",
  "guarantor.employmentType": "正社員",
  "guarantor.annualIncome": "520",
  "guarantor.yearsEmployed": "12年",
  "guarantor.payday": "25",
  "emergencyContact.furigana": "ヤマダ ハナコ",
  "emergencyContact.name": "山田 花子",
  "emergencyContact.gender": "女",
  "emergencyContact.spouse": "無",
  "emergencyContact.relationship": "母",
  "emergencyContact.birthDate": "1965年5月5日",
  "emergencyContact.postalCode": "1540024",
  "emergencyContact.address": "東京都世田谷区三軒茶屋2-3-4",
  "emergencyContact.residenceYears": "10年",
  "emergencyContact.housingType": "家族所有",
  "emergencyContact.phone": "080-1234-5678",
  "emergencyContact.mobilePhone": "080-1234-5678",
  "emergencyContact.employerFurigana": "サクラカイゴ",
  "emergencyContact.employerName": "さくら介護株式会社",
  "emergencyContact.employerPhone": "03-9876-5432",
  "emergencyContact.employerAddress": "東京都渋谷区代々木1-2-3",
  "emergencyContact.occupation": "介護",
  "emergencyContact.employmentType": "契約社員",
  "emergencyContact.annualIncome": "380",
  "emergencyContact.yearsEmployed": "5年",
  "emergencyContact.payday": "25",
  "coOccupants.0.furigana": "ヤマダ アイ",
  "coOccupants.0.name": "山田 愛",
  "coOccupants.0.relationship": "妻",
  "coOccupants.0.birthDate": "1992年2月2日",
  "coOccupants.0.phone": "080-2222-3333",
  "coOccupants.0.employerName": "青山デザイン株式会社",
  "coOccupants.1.furigana": "ヤマダ ソウタ",
  "coOccupants.1.name": "山田 蒼太",
  "coOccupants.1.relationship": "子",
  "coOccupants.1.birthDate": "2018年8月8日",
  "coOccupants.1.phone": "なし",
  "coOccupants.1.employerName": "港区立小学校",
  "coOccupants.2.furigana": "ヤマダ ミオ",
  "coOccupants.2.name": "山田 美緒",
  "coOccupants.2.relationship": "子",
  "coOccupants.2.birthDate": "2021年3月3日",
  "coOccupants.2.phone": "なし",
  "coOccupants.2.employerName": "保育園",
  "broker.companyName": "Cherry Investment株式会社",
  "broker.address": "東京都港区赤坂1-2-3",
  "broker.phone": "03-6234-5678",
  "broker.staffName": "田中 健一",
  "management.companyName": "港区グランド管理株式会社",
  "management.address": "東京都港区芝公園2-2-2",
  "management.phone": "03-5555-6666",
  "management.staffName": "佐藤 管理",
};

export const COMPLETE_DRAFT_DEFAULTS: Record<string, string> = {
  "company_option.zenhoren_collection_service": "利用する",
  "company_option.zenhoren_initial_fee": "賃料50%",
  "company_option.nihon_safety_product": "プラス1（保証人あり）",
  "company_option.nihon_safety_payment_method": "月払い",
  "company_option.j_lease_product_plan": "住居用プラン",
  "company_option.j_lease_rent_transfer": "利用する",
  "company_option.insure_smart_support": "居住用50",
  "company_option.insure_single_person": "該当なし",
  "company_option.friends_plan_type": "住居用標準プラン",
  "company_option.friends_consent": "確認済み",
  "company_option.friends_collection_agency": "利用する",
  "company_option.friends_single_rider": "なし",
  "company_option.friends_notes": "QA 完成確認",
};
