export const ACTIVE_TENANT_COOKIE_NAME = "brokerdesk_tenant_id";

export const TENANT_ROLES = [
  "platform_owner",
  "tenant_owner",
  "tenant_admin",
  "manager",
  "broker",
  "data_operator",
  "reviewer",
  "viewer",
] as const;

export type TenantRole = (typeof TENANT_ROLES)[number];

export type TenantCapabilityPreset = "company_owner" | "company_form_admin" | "ordinary_member";

export function tenantRoleForCapabilityPreset(capability: TenantCapabilityPreset): TenantRole {
  if (capability === "company_owner") return "tenant_owner";
  if (capability === "company_form_admin") return "manager";
  return "broker";
}

export const TENANT_PERMISSION_ACTIONS = [
  "tenant.read",
  "tenant.update_settings",
  "tenant.manage_billing",
  "member.invite",
  "member.update_role",
  "member.remove",
  "audit.view",
  "case.create",
  "case.read_own",
  "case.read_assigned",
  "case.read_team",
  "case.read_all",
  "case.update_own",
  "case.update_assigned",
  "case.assign",
  "case.close",
  "case.delete",
  "source.upload",
  "source.read",
  "source.delete",
  "source.download_original",
  "extract.run",
  "extract.view_result",
  "extract.accept_result",
  "extract.override_result",
  "extract.reject_result",
  "record.read",
  "record.read_sensitive",
  "record.update",
  "record.archive",
  "record.confirm",
  "record.mark_unknown",
  "record.resolve_conflict",
  "review_task.create",
  "review_task.resolve",
  "review_task.approve",
  "output.preview",
  "output.create_draft",
  "output.update_draft",
  "output.generate_final",
  "output.download_final",
  "output.delete",
  "template.view",
  "template.copy_official",
  "template.edit_draft",
  "template.ai_prematch",
  "template.publish",
  "template.rollback",
  "template.archive",
  "template.manage_official",
  "ai.extract",
  "ai.review_assist",
  "ai.field_prematch",
  "ai.preflight",
  "ai.experience_review",
  "ai.override_existing_values",
] as const;

export type TenantPermissionAction = (typeof TENANT_PERMISSION_ACTIONS)[number];

const FULL_TENANT_ACTIONS: TenantPermissionAction[] = TENANT_PERMISSION_ACTIONS.filter(
  (action) => action !== "template.manage_official",
);

const ROLE_PERMISSIONS: Record<TenantRole, TenantPermissionAction[]> = {
  platform_owner: [...TENANT_PERMISSION_ACTIONS],
  tenant_owner: FULL_TENANT_ACTIONS,
  tenant_admin: FULL_TENANT_ACTIONS.filter(
    (action) => action !== "tenant.manage_billing" && action !== "template.manage_official",
  ),
  manager: [
    "tenant.read",
    "audit.view",
    "case.create",
    "case.read_assigned",
    "case.read_team",
    "case.update_assigned",
    "case.assign",
    "source.upload",
    "source.read",
    "source.download_original",
    "extract.run",
    "extract.view_result",
    "extract.accept_result",
    "extract.override_result",
    "extract.reject_result",
    "record.read",
    "record.read_sensitive",
    "record.update",
    "record.archive",
    "record.confirm",
    "record.mark_unknown",
    "record.resolve_conflict",
    "review_task.create",
    "review_task.resolve",
    "review_task.approve",
    "output.preview",
    "output.create_draft",
    "output.update_draft",
    "output.generate_final",
    "output.download_final",
    "template.view",
    "template.copy_official",
    "template.edit_draft",
    "template.publish",
    "template.rollback",
    "template.archive",
    "ai.extract",
    "ai.review_assist",
    "ai.preflight",
  ],
  broker: [
    "tenant.read",
    "case.create",
    "case.read_own",
    "case.read_assigned",
    "case.update_own",
    "case.update_assigned",
    "source.upload",
    "source.read",
    "source.download_original",
    "extract.run",
    "extract.view_result",
    "extract.accept_result",
    "record.read",
    "record.read_sensitive",
    "record.update",
    "record.confirm",
    "record.mark_unknown",
    "record.resolve_conflict",
    "review_task.create",
    "review_task.resolve",
    "output.preview",
    "output.create_draft",
    "output.update_draft",
    "template.view",
    "template.copy_official",
    "ai.extract",
    "ai.review_assist",
    "ai.preflight",
  ],
  data_operator: [
    "tenant.read",
    "case.create",
    "case.read_assigned",
    "case.update_assigned",
    "source.upload",
    "source.read",
    "source.download_original",
    "extract.run",
    "extract.view_result",
    "extract.accept_result",
    "record.read",
    "record.update",
    "record.confirm",
    "record.mark_unknown",
    "record.resolve_conflict",
    "review_task.create",
    "review_task.resolve",
    "output.preview",
    "output.create_draft",
    "output.update_draft",
    "template.view",
    "template.copy_official",
    "ai.extract",
    "ai.review_assist",
  ],
  reviewer: [
    "tenant.read",
    "case.read_assigned",
    "source.read",
    "source.download_original",
    "extract.view_result",
    "extract.accept_result",
    "extract.override_result",
    "extract.reject_result",
    "record.read",
    "record.read_sensitive",
    "record.confirm",
    "record.mark_unknown",
    "record.resolve_conflict",
    "review_task.resolve",
    "review_task.approve",
    "output.preview",
    "output.generate_final",
    "output.download_final",
    "template.view",
    "template.copy_official",
  ],
  viewer: [
    "tenant.read",
    "case.read_assigned",
    "source.read",
    "extract.view_result",
    "record.read",
    "output.preview",
    "template.view",
    "template.copy_official",
  ],
};

export function isTenantRole(value: string): value is TenantRole {
  return (TENANT_ROLES as readonly string[]).includes(value);
}

export function roleHasTenantPermission(role: TenantRole, action: TenantPermissionAction) {
  return ROLE_PERMISSIONS[role].includes(action);
}

export function roleHasAllTenantPermissions(role: TenantRole, actions: readonly TenantPermissionAction[]) {
  return actions.every((action) => roleHasTenantPermission(role, action));
}

export function listTenantRolePermissions(role: TenantRole): TenantPermissionAction[] {
  return [...ROLE_PERMISSIONS[role]];
}

const CAPABILITY_PERMISSIONS: Record<TenantCapabilityPreset, TenantPermissionAction[]> = {
  company_owner: [...FULL_TENANT_ACTIONS],
  company_form_admin: [
    "tenant.read",
    "audit.view",
    "case.create",
    "case.read_assigned",
    "case.read_team",
    "case.update_assigned",
    "case.assign",
    "source.upload",
    "source.read",
    "source.download_original",
    "extract.run",
    "extract.view_result",
    "extract.accept_result",
    "extract.override_result",
    "extract.reject_result",
    "record.read",
    "record.read_sensitive",
    "record.update",
    "record.archive",
    "record.confirm",
    "record.mark_unknown",
    "record.resolve_conflict",
    "review_task.create",
    "review_task.resolve",
    "review_task.approve",
    "output.preview",
    "output.create_draft",
    "output.update_draft",
    "output.generate_final",
    "output.download_final",
    "template.view",
    "template.copy_official",
    "template.edit_draft",
    "template.publish",
    "template.rollback",
    "template.archive",
    "ai.extract",
    "ai.review_assist",
    "ai.preflight",
  ],
  ordinary_member: [
    "tenant.read",
    "case.create",
    "case.read_own",
    "case.read_assigned",
    "case.update_own",
    "case.update_assigned",
    "source.upload",
    "source.read",
    "source.download_original",
    "extract.run",
    "extract.view_result",
    "extract.accept_result",
    "record.read",
    "record.read_sensitive",
    "record.update",
    "record.confirm",
    "record.mark_unknown",
    "record.resolve_conflict",
    "review_task.create",
    "review_task.resolve",
    "output.preview",
    "output.create_draft",
    "output.update_draft",
    "output.generate_final",
    "output.download_final",
    "template.view",
    "template.copy_official",
    "ai.extract",
    "ai.review_assist",
    "ai.preflight",
  ],
};

export function capabilityHasTenantPermission(capability: TenantCapabilityPreset, action: TenantPermissionAction) {
  return CAPABILITY_PERMISSIONS[capability].includes(action);
}

export function listTenantCapabilityPermissions(capability: TenantCapabilityPreset) {
  return [...CAPABILITY_PERMISSIONS[capability]];
}
